### PR TITLE
918: Update annotations 

### PR DESCRIPTION
**Pull request by shaunharrisonFR**
Some annotations are now obsolete

Updating and increasing nginx version 

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/918

### CODE REVIEW

**Comment by shaunharrisonFR** [comment]
@BohoCode @dbadham-fr @jorgesanchezperez 

I'm not too clued up on these headers buffers and what not, but seen in some examples online they are stating a integer before the buffer size, so instead of 128k the value would be 4 128k

We don't have this in the SAAS product where the change has been made, but just checking we aren't going to need this here

**Comment by dbadham-fr** [comment]
Can you find a link to the documentation for the version we are using and see what it says please?

**Comment by shaunharrisonFR** [comment]
https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

**Comment by dbadham-fr** [comment]
So according to that doc the format is: `large_client_header_buffers number size;`

Therefore you need to specify the number of buffers, I believe that 4 is the default. Have you tested this PR out? I would assume nginx would be raising errors saying invalid syntax etc

**Comment by shaunharrisonFR** [comment]
Just had another look as SAAS and yeah they are using `4 16k`
https://github.com/ForgeCloud/ob-deploy/blob/master/client_releases/applications/ingress-nginx/values.yaml#L75

Not sure if we want to go with that instead or stick to 128k as I believe from the docs it says you still can't exceed the max of one of the buffers 

Havent put it into argocd yet, wanted to get this checked first

**Comment by dbadham-fr** [comment]
Let's do `4 128k`, we need big buffers for all of the JWTs that are sent in headers.

**Comment by shaunharrisonFR** [comment]
Ready for re review @dbadham-fr

**Review by dbadham-fr — APPROVED** [review]

**Pull request merged**
